---
- description: 
  buttons: submit,cancel
  label: VMware - ReconfigVM_HotAddEnabled
  dialog_tabs:
  - description: 
    display: edit
    label: VMware - ReconfigVM_HotAddEnabled
    display_method: 
    display_method_options: 
    position: 0
    dialog_groups:
    - description: 
      display: edit
      label: VM Information
      display_method: 
      display_method_options: 
      position: 0
      dialog_fields:
      - name: cpuHotAddEnabled
        description: 
        type: DialogFieldRadioButton
        data_type: string
        notes: 
        notes_display: 
        display: edit
        display_method: 
        display_method_options: {}
        required: true
        required_method: 
        required_method_options: {}
        default_value: 'true'
        values:
        - - 'false'
          - 'False'
        - - 'true'
          - 'True'
        values_method: 
        values_method_options: {}
        options:
          :sort_by: :description
          :sort_order: :ascending
        label: cpuHotAddEnabled *
        position: 0
        validator_type: 
        validator_rule: 
        reconfigurable: 
        dynamic: 
        show_refresh_button: 
        load_values_on_init: 
        read_only: 
        auto_refresh: 
        trigger_auto_refresh: 
        resource_action_fqname: ''
      - name: memoryHotAddEnabled
        description: 
        type: DialogFieldRadioButton
        data_type: string
        notes: 
        notes_display: 
        display: edit
        display_method: 
        display_method_options: {}
        required: true
        required_method: 
        required_method_options: {}
        default_value: 'true'
        values:
        - - 'false'
          - 'False'
        - - 'true'
          - 'True'
        values_method: 
        values_method_options: {}
        options:
          :sort_by: :description
          :sort_order: :ascending
        label: memoryHotAddEnabled *
        position: 1
        validator_type: 
        validator_rule: 
        reconfigurable: 
        dynamic: 
        show_refresh_button: 
        load_values_on_init: 
        read_only: 
        auto_refresh: 
        trigger_auto_refresh: 
        resource_action_fqname: ''
