---
- description: 
  buttons: submit,cancel
  label: VMware - ReconfigVM_GuestId
  dialog_tabs:
  - description: 
    display: edit
    label: VMware - ReconfigVM_GuestId
    display_method: 
    display_method_options: 
    position: 0
    dialog_groups:
    - description: 
      display: edit
      label: VM Information
      display_method: 
      display_method_options: 
      position: 0
      dialog_fields:
      - name: new_guestid
        description: 
        type: DialogFieldDropDownList
        data_type: string
        notes: 
        notes_display: 
        display: edit
        display_method: 
        display_method_options: {}
        required: true
        required_method: 
        required_method_options: {}
        default_value: rhel7_64Guest
        values:
        - - centos64Guest
          - CentOS (64-bit)
        - - fedora64Guest
          - 'Fedora Linux (64 bit) '
        - - freebsd64Guest
          - 'FreeBSD x64 '
        - - opensuse64Guest
          - 'OpenSUSE Linux (64 bit) '
        - - rhel7_64Guest
          - 'Red Hat Enterprise Linux 7 (64 bit) '
        - - solaris11_64Guest
          - 'Solaris 11 (64 bit) '
        - - sles12_64Guest
          - 'Suse Linux Enterprise Server 12 (64 bit) '
        - - windows7_64Guest
          - 'Windows 7 (64 bit) '
        - - windows8Server64Guest
          - 'Windows 8 Server (64 bit) '
        - - otherLinux64Guest
          - Linux (64 bit)
        values_method: 
        values_method_options: {}
        options:
          :sort_by: :description
          :sort_order: :ascending
        label: New GuestId *
        position: 0
        validator_type: 
        validator_rule: 
        reconfigurable: 
        dynamic: 
        show_refresh_button: 
        load_values_on_init: 
        read_only: 
        auto_refresh: 
        trigger_auto_refresh: 
        resource_action_fqname: ''
